### ISSUE TITLE
Client version 0.3 with loop mode

### ISSUE THREAD

**Issue by Oremuss** [rtr-nettest/open-rmbt#10]
Hello,

I have found weird behaviour using loop mode. I have measured my LTE in my kitchen  two days in a row. 
Now I have found some blank lines (not filled in database), where the app didnt record any measurments.
Measurement was every 15 minutes. From 207 measuements ( druing 2 days) there are 9 empty ( or missing) rows. There is no patern, one missing is at 02:56 (in the morning) other 13:52, previous day at 14:36 and 22:54 and so on. 

But they all have in common different client version. For good measurements client version is **1.2.1** and for these "wrong" measurements is client version **0.3**. How can there be different client version?

 Also in column _status_ is written "STARTED", the rows contain some more information like time, and some couple informations, but geolocation is missing, IP osf server is missing, no spead or ping measurement. I can provide output in CSV from database if wanted.

**Comment by cproof** [comment]
Hello,

sorry for responding late.

On the client version: My suspicion is that the client on registration sends the lowest version its compatible with (0.3) while updating the actual server version used (1.2.1) on finished tests. The actual used version is only available after the connection to the test server was successful, so that could be the cause.

> Also in column status is written "STARTED", the rows contain some more information like time, and some couple informations, but geolocation is missing, IP osf server is missing, no spead or ping measurement. I can provide output in CSV from database if wanted.

This is actually by design. On the test request (=the client registering with the ControlServer to conduct a new test) some basic information is transmitted and stored, to allow for easier trouble-shooting. As it seems that for these tests, the measurement itself was not completed, the other information is missing.

**Comment by Oremuss** [comment]
Yes I manage to find that 0.3 reference. I suspect it has something to do with my notebook connection. Since I installed all dependencies, ran servers, I noticed a small random disconnections in web browser. It is barely noticable but it is random and may cause all this. Anyway I close this issue since it looks like local problem, not problem with app.
